### ISSUE TITLE
This immediately has my interest,

### ISSUE THREAD

**Issue by FrostKnight** [CoffeeBrewer64/coffeeDS#1]
Let me know, if you get it up and running on a beta level.

I don't have programming skills regarding most things beyond compiling and using usually tho.

Not an expert at linux lol.

But anywho, I appreciate you using a non-bloated programming language to build this.

And not something like java, javascript, rust, etc...

I hope you will make the dependencies as small as possible, like Noods or New-DS as its pronounced.

This being said, I will be watching interested.

**Comment by CoffeeBrewer64** [comment]
> Let me know, if you get it up and running on a beta level.
> 
> I don't have programming skills regarding most things beyond compiling and using usually tho.
> 
> Not an expert at linux lol.
> 
> But anywho, I appreciate you using a non-bloated programming language to build this.
> 
> And not something like java, javascript, rust, etc...
> 
> I hope you will make the dependencies as small as possible, like Noods or New-DS as its pronounced.
> 
> This being said, I will be watching interested.

Yay! Thanks for the interest!

One day I'll make a Windows build. Once there's at least 10% compatibility I will make it.

As for the choice of using C, it's the only language I properly know, excluding Lua.

By the by, how did you discover this project?

**Comment by FrostKnight** [comment]
> > Let me know, if you get it up and running on a beta level.
> > I don't have programming skills regarding most things beyond compiling and using usually tho.
> > Not an expert at linux lol.
> > But anywho, I appreciate you using a non-bloated programming language to build this.
> > And not something like java, javascript, rust, etc...
> > I hope you will make the dependencies as small as possible, like Noods or New-DS as its pronounced.
> > This being said, I will be watching interested.
> 
> Yay! Thanks for the interest!
> 
> One day I'll make a Windows build. Once there's at least 10% compatibility I will make it.
> 
> As for the choice of using C, it's the only language I properly know, excluding Lua.
> 
> By the by, how did you discover this project?

Looking for alternatives to melonDS and so I searched for ds emulators on github.

I use linux currently, but my idea of a linux distro is more in line with BSD thinking than linux thinking...

Look up Hyperbola and see how many bloated linux frameworks they chopped off and you will get what I mean...

;)

When I said not an expert, I meant I haven't really learned any programming languages btw.

xD  

I don't use windows for the same reason I don't use rpm based distros, google like operating systems, apple like operating systems and FreeBSD...

Too bloated!

I do have respect though for OpenBSD also though. 

But anywho, that's my long winded answer and more beyond that. ;)
